# Generated by Django 3.0.5 on 2021-02-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20210225_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(
                help_text=('Slug должен быть уникальным и не превышать'
                           + ' 100 символов'),
                max_length=100, unique=True,
                verbose_name='Идентификатор страницы жанра'),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(
                blank=True,
                help_text='Вы можете выбрать категорию для этого произведения',
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='titles', to='api.Category',
                verbose_name='Название категории'),
        ),
    ]
