# Generated by Django 3.0.5 on 2021-02-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210225_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id', '-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id', '-pub_date']},
        ),
    ]
