# Generated by Django 3.0.5 on 2021-02-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_remove_title_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersToRegister',
            fields=[
                ('email', models.EmailField(
                    max_length=254,
                    primary_key=True,
                    serialize=False,
                    unique=True)),
                ('confirmation_code', models.UUIDField(
                    blank=True,
                    null=True,
                    verbose_name='Код подтверждения')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True,
                                   verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True,
                                   verbose_name='Фамилия'),
        ),
    ]
