# Generated by Django 3.0.5 on 2021-02-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210225_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersToRegister',
            new_name='UserToRegister',
        ),
    ]
